// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundBlurIn': string;
  'backgroundContainer': string;
  'pageContainer': string;
  'teamDescriptionBody': string;
}
export const cssExports: CssExports;
export default cssExports;
