// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navbarContainer': string;
  'navbarMenuItem': string;
}
export const cssExports: CssExports;
export default cssExports;
